// web-blog-v2/app/admin/(dashboard)/ai-management/models/page.tsx
'use client';

export const dynamic = 'force-dynamic';

import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import {
  adminCreateAIModel,
  adminDeleteAIModel,
  adminListAIModels,
  adminUpdateAIModel,
  type AIModel,
} from '@/lib/api/admin/ai-management';
import { formatDate } from '@/lib/date';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { AdminTablePagination } from '@/components/admin/table-cells/AdminTablePagination';

const DEFAULT_FORM = { name: '', display_name: '', provider: '', endpoint: '', api_key: '', max_tokens: 4096, temperature: 0.7, is_active: true };

export default function AdminAIModelsPage() {
  const [items, setItems] = useState<AIModel[]>([]);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [total, setTotal] = useState(0);
  const [name, setName] = useState('');
  const [provider, setProvider] = useState('');
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<AIModel | null>(null);
  const [form, setForm] = useState(DEFAULT_FORM);

  const fetchList = async () => {
    try {
      const res = await adminListAIModels({ page, page_size: pageSize, name: name || undefined, provider: provider || undefined });
      setItems(res.list || []);
      setTotal(res.total_items || 0);
    } catch {
      setItems([]);
      setTotal(0);
      toast.error('获取AI模型列表失败');
    }
  };

  useEffect(() => {
    adminListAIModels({ page, page_size: pageSize, name: name || undefined, provider: provider || undefined })
      .then((res) => {
        setItems(res.list || []);
        setTotal(res.total_items || 0);
      })
      .catch(() => {
        setItems([]);
        setTotal(0);
        toast.error('获取AI模型列表失败');
      });
  }, [page, pageSize, name, provider]);

  const onSearch = () => {
    setPage(1);
    void fetchList();
  };

  const onAdd = () => {
    setEditing(null);
    setForm(DEFAULT_FORM);
    setOpen(true);
  };

  const onEdit = (item: AIModel) => {
    setEditing(item);
    setForm({
      name: item.name || '',
      display_name: item.display_name || '',
      provider: item.provider || '',
      endpoint: item.endpoint || '',
      api_key: item.api_key || '',
      max_tokens: item.max_tokens || 4096,
      temperature: item.temperature || 0.7,
      is_active: item.is_active ?? true,
    });
    setOpen(true);
  };

  const onSubmit = async () => {
    if (!form.name.trim() || !form.display_name.trim() || !form.provider.trim()) {
      toast.error('请填写模型名称、显示名称和提供商');
      return;
    }

    try {
      if (editing) {
        await adminUpdateAIModel({ id: editing.id, ...form });
        toast.success('更新成功');
      } else {
        await adminCreateAIModel(form);
        toast.success('创建成功');
      }
      setOpen(false);
      await fetchList();
    } catch {
      toast.error('操作失败');
    }
  };

  const onDelete = async (id: number) => {
    try {
      await adminDeleteAIModel(id);
      toast.success('删除成功');
      await fetchList();
    } catch {
      toast.error('删除失败');
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>AI模型管理</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="flex flex-wrap items-center justify-between gap-2"><div><Button onClick={onAdd}>新增模型</Button></div><div className="flex items-center gap-2"><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="模型名称" className="w-52" /><Input value={provider} onChange={(e) => setProvider(e.target.value)} placeholder="提供商" className="w-52" /><Button onClick={onSearch}>搜索</Button></div></div>

        <Table>
          <TableHeader><TableRow><TableHead>ID</TableHead><TableHead>模型名称</TableHead><TableHead>显示名称</TableHead><TableHead>提供商</TableHead><TableHead>端点</TableHead><TableHead>最大Token数</TableHead><TableHead>温度参数</TableHead><TableHead>状态</TableHead><TableHead>创建时间</TableHead><TableHead>操作</TableHead></TableRow></TableHeader>
          <TableBody>{items.map((it) => (
            <TableRow key={it.id}><TableCell>{it.id}</TableCell><TableCell>{it.name}</TableCell><TableCell>{it.display_name || '-'}</TableCell><TableCell>{it.provider || '-'}</TableCell><TableCell className="max-w-[220px] truncate">{it.endpoint || '-'}</TableCell><TableCell>{it.max_tokens || '-'}</TableCell><TableCell>{it.temperature ?? '-'}</TableCell><TableCell>{it.is_active ? '启用' : '禁用'}</TableCell><TableCell>{formatDate(it.created_at)}</TableCell><TableCell className="space-x-2"><Button size="sm" variant="outline" onClick={() => onEdit(it)}>编辑</Button><Button size="sm" variant="destructive" onClick={() => onDelete(it.id)}>删除</Button></TableCell></TableRow>
          ))}</TableBody>
        </Table>

        <AdminTablePagination page={page} pageSize={pageSize} total={total} onPageChange={setPage} onPageSizeChange={(size) => { setPageSize(size); setPage(1); }} />

        <Dialog open={open} onOpenChange={setOpen}>
          <DialogContent>
            <DialogHeader><DialogTitle>{editing ? '编辑模型' : '新增模型'}</DialogTitle></DialogHeader>
            <div className="space-y-3">
              <Input placeholder="模型名称" value={form.name} onChange={(e) => setForm((p) => ({ ...p, name: e.target.value }))} />
              <Input placeholder="显示名称" value={form.display_name} onChange={(e) => setForm((p) => ({ ...p, display_name: e.target.value }))} />
              <Input placeholder="提供商" value={form.provider} onChange={(e) => setForm((p) => ({ ...p, provider: e.target.value }))} />
              <Input placeholder="API端点" value={form.endpoint} onChange={(e) => setForm((p) => ({ ...p, endpoint: e.target.value }))} />
              <Input placeholder="API密钥" value={form.api_key} onChange={(e) => setForm((p) => ({ ...p, api_key: e.target.value }))} />
              <Input placeholder="最大Token数" value={String(form.max_tokens)} onChange={(e) => setForm((p) => ({ ...p, max_tokens: Number(e.target.value) || 0 }))} />
              <Input placeholder="温度参数" value={String(form.temperature)} onChange={(e) => setForm((p) => ({ ...p, temperature: Number(e.target.value) || 0 }))} />
              <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.is_active} onChange={(e) => setForm((p) => ({ ...p, is_active: e.target.checked }))} /> 启用</label>
            </div>
            <DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>取消</Button><Button onClick={onSubmit}>确定</Button></DialogFooter>
          </DialogContent>
        </Dialog>
      </CardContent>
    </Card>
  );
}

// web-blog/src/views/dashboard/ai-management/models.vue
<template>
  <div class="ai-model-management">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>AI模型管理</span>
          <el-button type="primary" @click="handleAdd">新增模型</el-button>
        </div>
      </template>

      <!-- 搜索区域 -->
      <el-form :inline="true" :model="searchForm" class="search-form">
        <el-form-item label="模型名称">
          <el-input v-model="searchForm.name" placeholder="请输入模型名称" clearable />
        </el-form-item>
        <el-form-item label="提供商">
          <el-input v-model="searchForm.provider" placeholder="请输入提供商" clearable />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="handleSearch">搜索</el-button>
          <el-button @click="handleReset">重置</el-button>
        </el-form-item>
      </el-form>

      <!-- 表格 -->
      <el-table :data="tableData" v-loading="loading" border stripe>
        <el-table-column prop="id" label="ID" width="80" />
        <el-table-column prop="name" label="模型名称" />
        <el-table-column prop="display_name" label="显示名称" />
        <el-table-column prop="provider" label="提供商" />
        <el-table-column prop="endpoint" label="API端点" show-overflow-tooltip />
        <el-table-column prop="max_tokens" label="最大Token数" width="120" />
        <el-table-column prop="temperature" label="温度参数" width="100" />
        <el-table-column prop="is_active" label="状态" width="100">
          <template #default="{ row }">
            <el-tag :type="row.is_active ? 'success' : 'danger'">
              {{ row.is_active ? '启用' : '禁用' }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="created_at" label="创建时间" width="180">
          <template #default="{ row }">
            {{ formatDate(row.created_at) }}
          </template>
        </el-table-column>
        <el-table-column label="操作" width="200" fixed="right">
          <template #default="{ row }">
            <el-button type="primary" size="small" @click="handleEdit(row)">编辑</el-button>
            <el-button type="danger" size="small" @click="handleDelete(row)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>

      <!-- 分页 -->
      <div class="pagination-wrapper">
        <el-pagination
          v-model:current-page="pagination.page"
          v-model:page-size="pagination.page_size"
          :page-sizes="[10, 20, 50, 100]"
          :total="pagination.total"
          layout="total, sizes, prev, pager, next, jumper"
          @size-change="handleSizeChange"
          @current-change="handleCurrentChange"
        />
      </div>
    </el-card>

    <!-- 新增/编辑对话框 -->
    <el-dialog
      v-model="dialogVisible"
      :title="dialogTitle"
      width="600px"
      @close="handleDialogClose"
    >
      <el-form
        ref="formRef"
        :model="form"
        :rules="rules"
        label-width="120px"
      >
        <el-form-item label="模型名称" prop="name">
          <el-input v-model="form.name" placeholder="请输入模型名称" />
        </el-form-item>
        <el-form-item label="显示名称" prop="display_name">
          <el-input v-model="form.display_name" placeholder="请输入显示名称" />
        </el-form-item>
        <el-form-item label="提供商" prop="provider">
          <el-input v-model="form.provider" placeholder="请输入提供商" />
        </el-form-item>
        <el-form-item label="API端点" prop="endpoint">
          <el-input v-model="form.endpoint" placeholder="请输入API端点" />
        </el-form-item>
        <el-form-item label="API密钥" prop="api_key">
          <el-input v-model="form.api_key" placeholder="请输入API密钥" show-password />
        </el-form-item>
        <el-form-item label="最大Token数" prop="max_tokens">
          <el-input-number v-model="form.max_tokens" :min="1" :max="100000" />
        </el-form-item>
        <el-form-item label="温度参数" prop="temperature">
          <el-input-number
            v-model="form.temperature"
            :min="0"
            :max="2"
            :precision="2"
            :step="0.1"
          />
        </el-form-item>
        <el-form-item label="状态" prop="is_active">
          <el-switch v-model="form.is_active" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" @click="handleSubmit" :loading="submitLoading">
          确定
        </el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { ElMessage, ElMessageBox, type FormInstance, type FormRules } from 'element-plus'
import { aiModelApi } from '@/api/ai-management'
import { formatDate } from '@/utils/date'

// 响应式数据
const loading = ref(false)
const submitLoading = ref(false)
const dialogVisible = ref(false)
const dialogTitle = ref('')
const formRef = ref<FormInstance>()

// 搜索表单
const searchForm = reactive({
  name: '',
  provider: ''
})

// 分页数据
const pagination = reactive({
  page: 1,
  page_size: 10,
  total: 0
})

// 表格数据
const tableData = ref([])

// 表单数据
const form = reactive({
  id: 0,
  name: '',
  display_name: '',
  provider: '',
  endpoint: '',
  api_key: '',
  max_tokens: 4096,
  temperature: 0.7,
  is_active: true
})

// 表单验证规则
const rules: FormRules = {
  name: [
    { required: true, message: '请输入模型名称', trigger: 'blur' }
  ],
  display_name: [
    { required: true, message: '请输入显示名称', trigger: 'blur' }
  ],
  provider: [
    { required: true, message: '请输入提供商', trigger: 'blur' }
  ]
}

// 获取列表数据
const getList = async () => {
  loading.value = true
  try {
    const params = {
      page: pagination.page,
      page_size: pagination.page_size,
      ...searchForm
    }
    const res = await aiModelApi.list(params)
    tableData.value = res.data.list
    pagination.total = res.data.total_items
  } catch (error) {
    console.error('获取AI模型列表失败:', error)
    ElMessage.error('获取AI模型列表失败')
  } finally {
    loading.value = false
  }
}

// 搜索
const handleSearch = () => {
  pagination.page = 1
  getList()
}

// 重置搜索
const handleReset = () => {
  Object.assign(searchForm, {
    name: '',
    provider: ''
  })
  pagination.page = 1
  getList()
}

// 新增
const handleAdd = () => {
  dialogTitle.value = '新增AI模型'
  resetForm()
  dialogVisible.value = true
}

// 编辑
const handleEdit = (row: any) => {
  dialogTitle.value = '编辑AI模型'
  Object.assign(form, row)
  dialogVisible.value = true
}

// 删除
const handleDelete = async (row: any) => {
  try {
    await ElMessageBox.confirm('确定要删除这个AI模型吗？', '提示', {
      type: 'warning'
    })
    
    await aiModelApi.delete(row.id)
    ElMessage.success('删除成功')
    getList()
  } catch (error) {
    if (error !== 'cancel') {
      console.error('删除AI模型失败:', error)
      ElMessage.error('删除失败')
    }
  }
}

// 提交表单
const handleSubmit = async () => {
  if (!formRef.value) return
  
  try {
    await formRef.value.validate()
    submitLoading.value = true
    
    if (form.id) {
      await aiModelApi.update(form)
      ElMessage.success('更新成功')
    } else {
      await aiModelApi.create(form)
      ElMessage.success('创建成功')
    }
    
    dialogVisible.value = false
    getList()
  } catch (error) {
    console.error('提交失败:', error)
    ElMessage.error('提交失败')
  } finally {
    submitLoading.value = false
  }
}

// 重置表单
const resetForm = () => {
  Object.assign(form, {
    id: 0,
    name: '',
    display_name: '',
    provider: '',
    endpoint: '',
    api_key: '',
    max_tokens: 4096,
    temperature: 0.7,
    is_active: true
  })
  formRef.value?.clearValidate()
}

// 对话框关闭
const handleDialogClose = () => {
  resetForm()
}

// 分页大小改变
const handleSizeChange = (size: number) => {
  pagination.page_size = size
  pagination.page = 1
  getList()
}

// 当前页改变
const handleCurrentChange = (page: number) => {
  pagination.page = page
  getList()
}


// 初始化
onMounted(() => {
  getList()
})
</script>

<style scoped>
.ai-model-management {
  padding: 20px;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.search-form {
  margin-bottom: 20px;
}

.pagination-wrapper {
  margin-top: 20px;
  display: flex;
  justify-content: center;
}
</style>
